import type { Metadata } from "next"
import { Inter } from "next/font/google"
import QueryFetchProvider from "@/context/QueryFetchContext"
import SelectedContinentProvider from "@/context/SelectedContinentContext"
import "../styles/globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <QueryFetchProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </QueryFetchProvider>
  )
}
